### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd' 

### ISSUE THREAD

**Issue by LobsterMan** [openschemas/schemaorg#29]
**Describe the bug**
When trying to load the schemaorg module on windows, I get the following error ModuleNotFoundError: No module named 'pwd'

Apparently, the pwd module does not exist in windows versions of python.

it is being used in utils.py for get_userhome(). the code there can easily be replaced with a cross-platform solution:

def get_userhome():
    '''get the user home
    '''
    return str(Path.home())

**To Reproduce - on a windows machine**
pip install schemaorg
from schemaorg.main import Schema

**Expected behavior**

**Version of Python schemaorg**
0.0.22

**Comment by vsoch** [comment]
Th is is definitely the case that Windows doesn’t have pwd! Since you have windows, would you care to PR with a solution that works for you and I can make sure it still works on Linux? I also don’t think the schema.org database was updated for the last release so let me know if that’s an issue as well.

**Comment by vsoch** [comment]
But actually if the user home isn’t used for anything we could remove it entirely! I’m not sure why it’s needed - quick glance it doesn’t seem used.

**Comment by vsoch** [comment]
heyo @LobsterMan ! This PR should address your issue, and also add the latest (7.03) version. Would you care to test? https://github.com/openschemas/schemaorg/pull/30
